/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Teacher;

import Controller.Teacher.ManageCourseViewController;
import Model.Course;
import Model.User;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author BaDlUcK
 */
public class ManageCourseView extends javax.swing.JFrame {

    /**
     * Creates new form ManageCourseView
     */
    User authUser;
    Course course;
    ManageCourseViewController manageCourseViewController;
    int student_id = 0;

    public ManageCourseView(User user,Course course) {
        initComponents();
        setLocationRelativeTo(null);
        this.course = course;
        this.authUser=user;
        manageCourseViewController = new ManageCourseViewController(course, this);
        manageCourseViewController.initView();
    }

    public JTable getStudentsJTable() {
        return studentsJTable;
    }

    public void setStudentsJTable(JTable studentsJTable) {
        this.studentsJTable = studentsJTable;
    }

    public JTextField getFinalGradeJTextField() {
        return finalGradeJTextField;
    }

    public void setFinalGradeJTextField(JTextField finalGradeJTextField) {
        this.finalGradeJTextField = finalGradeJTextField;
    }

    public JTextField getMidtermGradeJTextField() {
        return midtermGradeJTextField;
    }

    public void setMidtermGradeJTextField(JTextField midtermGradeJTextField) {
        this.midtermGradeJTextField = midtermGradeJTextField;
    }

    public JLabel getSelectedStudentNameJLabel() {
        return selectedStudentNameJLabel;
    }

    public void setSelectedStudentNameJLabel(JLabel selectedStudentNameJLabel) {
        this.selectedStudentNameJLabel = selectedStudentNameJLabel;
    }

    public JLabel getTitleJLabel() {
        return titleJLabel;
    }

    public void setTitleJLabel(JLabel titleJLabel) {
        this.titleJLabel = titleJLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsJTable = new javax.swing.JTable();
        selectedStudentNameJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        finalGradeJTextField = new javax.swing.JTextField();
        midtermGradeJTextField = new javax.swing.JTextField();
        midtermExamJLabel = new javax.swing.JLabel();
        finalExamJLabel = new javax.swing.JLabel();
        deleteStudentJButton = new javax.swing.JButton();
        setGradeJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleJLabel.setText("Mange Course Page");

        studentsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Student Name", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentsJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentsJTable);
        if (studentsJTable.getColumnModel().getColumnCount() > 0) {
            studentsJTable.getColumnModel().getColumn(0).setMinWidth(0);
            studentsJTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            studentsJTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        selectedStudentNameJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectedStudentNameJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        midtermExamJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        midtermExamJLabel.setText("Midterm Exam Grade :");

        finalExamJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalExamJLabel.setText("Final Exam Grade :");

        deleteStudentJButton.setText("Delete Student");
        deleteStudentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentJButtonActionPerformed(evt);
            }
        });

        setGradeJButton.setText("Set Grade");
        setGradeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setGradeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(selectedStudentNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(midtermExamJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(midtermGradeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(finalExamJLabel)
                        .addGap(29, 29, 29)
                        .addComponent(finalGradeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setGradeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(deleteStudentJButton)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectedStudentNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(midtermExamJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midtermGradeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalExamJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalGradeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setGradeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteStudentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentsJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsJTableMouseClicked
        // TODO add your handling code here:
        student_id = manageCourseViewController.mouseClickedAction();
    }//GEN-LAST:event_studentsJTableMouseClicked

    private void setGradeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGradeJButtonActionPerformed
        // TODO add your handling code here:
        if (student_id == 0) {
            JOptionPane.showMessageDialog(this, "Please select a student");
        } else {
            int updated = manageCourseViewController.setGradeButtonAction();
            if (updated != -1) {
                JOptionPane.showMessageDialog(this, "Done the user has been updated");
                manageCourseViewController.clear();
                manageCourseViewController.updateTable();
                student_id = 0;
            }

        }
    }//GEN-LAST:event_setGradeJButtonActionPerformed

    private void deleteStudentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentJButtonActionPerformed
        // TODO add your handling code here:
         if (student_id == 0) {
            JOptionPane.showMessageDialog(this, "Please select a student");
        } else {
            int deleted = manageCourseViewController.deleteButtonAction();
            if (deleted != -1) {
                JOptionPane.showMessageDialog(this, "Done the user has been deleted");
                manageCourseViewController.clear();
                manageCourseViewController.updateTable();
                student_id = 0;
            }

        }
    }//GEN-LAST:event_deleteStudentJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TeacherCoursesView(authUser).setVisible(true);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defautitleJLabel="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteStudentJButton;
    private javax.swing.JLabel finalExamJLabel;
    private javax.swing.JTextField finalGradeJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel midtermExamJLabel;
    private javax.swing.JTextField midtermGradeJTextField;
    private javax.swing.JLabel selectedStudentNameJLabel;
    private javax.swing.JButton setGradeJButton;
    private javax.swing.JTable studentsJTable;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
