/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Admin;

import Controller.Admin.ManageCourseViewController;
import Model.Course;
import Model.User;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author BaDlUcK
 */
public class ManageCourseView extends javax.swing.JFrame  implements Observer{

    User authUser;
    Course course;
    ManageCourseViewController manageCourseViewController;

    public JLabel getCourseInfoJLabel1() {
        return courseInfoJLabel1;
    }

    public void setCourseInfoJLabel1(JLabel courseInfoJLabel1) {
        this.courseInfoJLabel1 = courseInfoJLabel1;
    }

    public JTextField getCapacityJTextField() {
        return capacityJTextField;
    }

    public void setCapacityJTextField(JTextField capacityJTextField) {
        this.capacityJTextField = capacityJTextField;
    }

    public JTextField getCourseNameJTextField() {
        return courseNameJTextField;
    }

    public void setCourseNameJTextField(JTextField courseNameJTextField) {
        this.courseNameJTextField = courseNameJTextField;
    }

    public JTable getCoursesJTabel() {
        return coursesJTabel;
    }

    public void setCoursesJTabel(JTable coursesJTabel) {
        this.coursesJTabel = coursesJTabel;
    }

    public JComboBox<String> getTeachersjComboBox1() {
        return teachersjComboBox1;
    }

    /**
     * Creates new form ManageCourseView
     */
    public void setTeachersjComboBox1(JComboBox<String> teachersjComboBox1) {
        this.teachersjComboBox1 = teachersjComboBox1;
    }

    public ManageCourseView(User user) {
        initComponents();
        setLocationRelativeTo(null);
        this.authUser=user;
        manageCourseViewController = new ManageCourseViewController(this);
        manageCourseViewController.initView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesJTabel = new javax.swing.JTable();
        courseNameJLabel = new javax.swing.JLabel();
        courseNameJTextField = new javax.swing.JTextField();
        capacityJLabel = new javax.swing.JLabel();
        capacityJTextField = new javax.swing.JTextField();
        teacherJLabel = new javax.swing.JLabel();
        teachersjComboBox1 = new javax.swing.JComboBox<>();
        AddCourseJButton = new javax.swing.JButton();
        updateJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        courseInfoJLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleJLabel.setText("Manage Courses");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        coursesJTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Course Name", "Teacher Name", "Capacity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        coursesJTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursesJTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(coursesJTabel);
        if (coursesJTabel.getColumnModel().getColumnCount() > 0) {
            coursesJTabel.getColumnModel().getColumn(0).setMinWidth(0);
            coursesJTabel.getColumnModel().getColumn(0).setMaxWidth(0);
            coursesJTabel.getColumnModel().getColumn(1).setResizable(false);
            coursesJTabel.getColumnModel().getColumn(2).setResizable(false);
            coursesJTabel.getColumnModel().getColumn(3).setResizable(false);
        }

        courseNameJLabel.setText("Course Name :");

        capacityJLabel.setText("Capacity :");

        teacherJLabel.setText("Teacher :");

        AddCourseJButton.setText("Add");
        AddCourseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCourseJButtonActionPerformed(evt);
            }
        });

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setText("Delete");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        courseInfoJLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        courseInfoJLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Course Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(teacherJLabel)
                                            .addComponent(capacityJLabel))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(teachersjComboBox1, 0, 106, Short.MAX_VALUE)
                                            .addComponent(capacityJTextField)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(courseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(courseNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseInfoJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddCourseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(updateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backJButton)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacityJLabel)
                            .addComponent(capacityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teacherJLabel)
                            .addComponent(teachersjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(courseInfoJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCourseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coursesJTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesJTabelMouseClicked
        // TODO add your handling code here:
        manageCourseViewController.mouseClickedAction();
    }//GEN-LAST:event_coursesJTabelMouseClicked

    private void AddCourseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCourseJButtonActionPerformed
        // TODO add your handling code here:
        int created = manageCourseViewController.addButtonAction();
        if (created != -1) {
            JOptionPane.showMessageDialog(this, "Done the course has been created");

        } else {
            JOptionPane.showMessageDialog(this, "Error empty fields");
        }

    }//GEN-LAST:event_AddCourseJButtonActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
        int updated = manageCourseViewController.updateButtonAction();
        if (updated != -1) {
            JOptionPane.showMessageDialog(this, "Done the user has been updated successfully !!");
        } else {
            JOptionPane.showMessageDialog(this, "There was an error");
        }

    }//GEN-LAST:event_updateJButtonActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        // TODO add your handling code here:
        int deleted = manageCourseViewController.deleteButtonAction();
        if (deleted != -1) {
            JOptionPane.showMessageDialog(this, "Done the user has been deleted successfully!!");
            manageCourseViewController.updateTable();
            manageCourseViewController.emptyFields();
        } else {
            JOptionPane.showMessageDialog(this, "There was an error");
        }
    }//GEN-LAST:event_deleteJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HomeView(authUser).setVisible(true);
    }//GEN-LAST:event_backJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCourseJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel capacityJLabel;
    private javax.swing.JTextField capacityJTextField;
    private javax.swing.JLabel courseInfoJLabel1;
    private javax.swing.JLabel courseNameJLabel;
    private javax.swing.JTextField courseNameJTextField;
    private javax.swing.JTable coursesJTabel;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel teacherJLabel;
    private javax.swing.JComboBox<String> teachersjComboBox1;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        manageCourseViewController.updateTable();
        manageCourseViewController.emptyFields();
    }
}
