/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Student;

import Controller.Student.StudentHomeViewController;
import Views.Teacher.*;
import Controller.Teacher.TeacherHomeViewController;
import Model.User;
import Views.LoginView;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author BaDlUcK
 */
public class StudentHomeView extends javax.swing.JFrame {

    /**
     * Creates new form TeacherHomeView
     */
    User authUser;
    StudentHomeViewController studentHomeViewController;

    public JButton getShowGradesJButton() {
        return showGradesJButton;
    }

    public void setShowGradesJButton(JButton showGradesJButton) {
        this.showGradesJButton = showGradesJButton;
    }

    public JButton getShowInfoJButton() {
        return showInfoJButton;
    }

    public void setShowInfoJButton(JButton showInfoJButton) {
        this.showInfoJButton = showInfoJButton;
    }
    
    public JLabel getImageJLabel() {
        return imageJLabel;
    }

   

    public void setImageJLabel(JLabel imageJLabel) {
        this.imageJLabel = imageJLabel;
    }

    public JLabel getWelcomeJLabel() {
        return welcomeJLabel;
    }

    public void setWelcomeJLabel(JLabel welcomeJLabel) {
        this.welcomeJLabel = welcomeJLabel;
    }

    public User getAuthUser() {
        return authUser;
    }

    public void setAuthUser(User authUser) {
        this.authUser = authUser;
    }

    public JLabel getStudentInfoJLabel() {
        return studentInfoJLabel;
    }

    public void setStudentInfoJLabel(JLabel teacherInfoJLabel) {
        this.studentInfoJLabel = teacherInfoJLabel;
    }
    
    public StudentHomeView(User user) {
        initComponents();
        setLocationRelativeTo(null);
        this.authUser=user;
        studentHomeViewController = new StudentHomeViewController(user, this);
        studentHomeViewController.initView();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageJLabel = new javax.swing.JLabel();
        titleJLabel = new javax.swing.JLabel();
        welcomeJLabel = new javax.swing.JLabel();
        studentInfoJLabel = new javax.swing.JLabel();
        updateInfoJButton = new javax.swing.JButton();
        coursesJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        showGradesJButton = new javax.swing.JButton();
        showInfoJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleJLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleJLabel.setText("Course System");

        welcomeJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcomeJLabel.setText("Welcome");

        studentInfoJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studentInfoJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        studentInfoJLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Info\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        updateInfoJButton.setText("Update Info");
        updateInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoJButtonActionPerformed(evt);
            }
        });

        coursesJButton.setText("Courses");
        coursesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesJButtonActionPerformed(evt);
            }
        });

        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        showGradesJButton.setText("Show Grades");
        showGradesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGradesJButtonActionPerformed(evt);
            }
        });

        showInfoJButton.setText("Show Info");
        showInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInfoJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(welcomeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(showGradesJButton)
                                        .addGap(28, 28, 28)
                                        .addComponent(showInfoJButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentInfoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(coursesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(updateInfoJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(welcomeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showGradesJButton)
                            .addComponent(showInfoJButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentInfoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateInfoJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coursesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoJButtonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_updateInfoJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        // TODO add your handling code here:
       this.dispose();
        new LoginView().setVisible(true);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void coursesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new StudentCourseView(authUser).setVisible(true);
    }//GEN-LAST:event_coursesJButtonActionPerformed

    private void showGradesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGradesJButtonActionPerformed
        // TODO add your handling code here:
        studentHomeViewController.showGradesAction();
    }//GEN-LAST:event_showGradesJButtonActionPerformed

    private void showInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInfoJButtonActionPerformed
        // TODO add your handling code here:
        studentHomeViewController.showInfoAction();
    }//GEN-LAST:event_showInfoJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coursesJButton;
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JButton showGradesJButton;
    private javax.swing.JButton showInfoJButton;
    private javax.swing.JLabel studentInfoJLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JButton updateInfoJButton;
    private javax.swing.JLabel welcomeJLabel;
    // End of variables declaration//GEN-END:variables
}
